
simulation:
  initial_state: [
# head
0., 0., 0.6, 0., 0., 0.,

# left arm
1.9, -0.7,  -2.8,  1.,  0., 0., 0.,

# left hand
0., 0., 0., 0., 0., 0., 0., 0.,

# right arm
1.5, -0.8, -2.6, 1.4, 0., 0., 0.,

# right hand
0., 0., 0., 0., 0., 0., 0., 0.
]
